
### Alle Aufträge anzeigen lassen
GET http://localhost:8080/auftrag

### Aufrtage erstellen
POST http://localhost:8080/auftrag
Content-Type: application/json

{
  "customerName" : "Herbert Wurst",
  "customerPlz": 1000,
  "customerStreet": "Wurststraße",
  "description": "Haus reparieren"
}

### Status über die Auftrags Id ändern
PUT http://localhost:8080/auftrag/status/1
Content-Type: application/json

{
  "status": "IN_ARBEIT"
}